#ifndef API_INC_API_CMDPARSER_H_
#define API_INC_API_CMDPARSER_H_

#include <stdbool.h>
#include "error.h"

#define CMDPARSER_ERR_INIT (ERR_BASE_CMDPARSER + 1)
#define CMDPARSER_ERR_INVALID_CMD (ERR_BASE_CMDPARSER + 2)
#define CMDPARSER_ERR_UNKNOWN_CMD (ERR_BASE_CMDPARSER + 3)
#define CMDPARSER_ERR_OVERFLOW (ERR_BASE_CMDPARSER + 4)
#define CMDPARSER_ERR_ARGS (ERR_BASE_CMDPARSER + 5)
#define CMDPARSER_ERR_INTERNAL (ERR_BASE_CMDPARSER + 6)
#define CMDPARSER_ERR_UNKNOWN (ERR_BASE_CMDPARSER + 7)

app_err_t cmdparser_init();

void cmdparser_read_cmd();

#endif /* API_INC_API_CMDPARSER_H_ */
